repos:
  # check yaml and end of file fixer
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  # nbqa autopep8 and ruff
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
    - id: nbqa-autopep8
      additional_dependencies: [autopep8==2.0.1]
    - id: nbqa-ruff
      additional_dependencies: [ruff==0.0.226]
